version: "3.8"

networks:
  valostats-website:
    driver: overlay

services:

  frontend:
    image: keinz/valostats-frontend:latest
    ports:
      - 8080:8080
    networks:
      - valostats-website

  backend:
    image: keinz/valostats-backend:latest
    ports:
      - 8081:8081
    networks:
      - valostats-website